<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblComment</name>
   <tag></tag>
   <elementGuidId>7e9e33ea-b7f1-4d23-a79a-ec1d22e8b7af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>input-comment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-qa-id='input-comment']</value>
   </webElementProperties>
</WebElementEntity>
